### ISSUE TITLE
为什么刷新之后跳回去上一页，应该是在当前页才对的啊

### ISSUE THREAD

**Issue by JaneTan44** [JooZh/vue-app-effect#1]
为什么刷新之后跳回去上一页，应该是在当前页才对的啊

**Comment by JooZh** [comment]
真实模拟App 的情况下是不存在刷新这种状态的，只有下拉刷新和上拉加载，并且刷新页面后sessionStorage 存储被清空，导致切换逻辑恢复初始化。
